version: "3"
services:
  nakama:
    container_name: nakama
    image: heroiclabs/nakama-prerelease
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address "y:a@127.0.0.1:5432/grizzly" &&
        exec /nakama/nakama --config /nakama/data/config.yml
    restart: always
    volumes:
      - ./data:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
